services:
  - type: web
    name: coupon-distribution-backend
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: COUPON_CLAIM_COOLDOWN_HOURS
        sync: false
      - key: MAX_COUPONS_PER_SESSION
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: LOG_LEVEL
        sync: false 